homeassistant:

frontend:

config:

lovelace:

history:

logbook:

map:

sun:

system_health:

api:

auth:

diagnostics:

file_upload:

image_upload:

onboarding:

repairs:

search:

websocket_api:

device_automation:

recorder:

person:

zone:

logger:
  default: info
  logs:
    custom_components.discord_chat_bridge: debug
